---
disabled_services:
  - ModemManager.service
  - atd.service
  - abrtd.service
  - abrt-journal-core.service
  - abrt-oops.service
  - abrt-vmcore.service
  - abrt-xorg.service
  - gssproxy.service
  - cups.service
  - cups.socket
  - cups.path
  - avahi-daemon.service
  - avahi-daemon.socket
  - bluetooth.service
  - switcheroo-control.service
...
