---
- name: Install various packages
  become: true
  block:
    - name: Install common packages (okular, vlc, kate, ...)
      become: true
      ansible.builtin.package:
        name:
          - python3-dnf # Needed for Ansible to interact with DNF.
          - gwenview
          - okular
          - vlc
          - firefox
          - kate
        state: present

    - name: Terminal tools (neovim, htop, wget, ...)
      become: true
      ansible.builtin.package:
        name:
          - neovim
          # - nmtui
          - curl
          - wget
          - tree
          - htop
          - btop
          - bat
          - nmap
        state: present

    - name: Development packages (git, gcc, make, ...)
      become: true
      ansible.builtin.package:
        name:
          - git
          - gcc-c++
          - gdb
          - cmake
          - make
          - valgrind
          - cppcheck
          - clang
          - clang-tools-extra
          - gmp
          - parallel
        state: present

    - name: Misc utilites (net-tools)
      become: true
      ansible.builtin.package:
        name:
          - net-tools # (ether-wake)
        state: present
...
