---
- name: Install various packages
  become: true
  block:
    - name: Install common packages
      become: true
      ansible.builtin.package:
        name:
          - python3-dnf # Needed for Ansible to interact with DNF.
          - gwenview
          - okular
          - vlc
          - firefox
          - kate
        state: present

    - name: Terminal tools
      become: true
      ansible.builtin.package:
        name:
          - neovim
          - curl
          - wget
          - tree
          - htop
          - btop
          - bat
          - nmap
        state: present

    - name: C++ Development
      become: true
      ansible.builtin.package:
        name:
          - gcc-c++
          - gdb
          - cmake
          - make
          - valgrind
          - cppcheck
          - clang
          - clang-tools-extra
        state: present
...
