- name: Install Librewolf via Flatpak
  community.general.flatpak:
    name: io.gitlab.librewolf-community
    state: present

- name: Install KeePassXC via Flatpak
  community.general.flatpak:
    name: org.keepassxc.KeePassXC
    state: present

- name: Install Visual Studio Code via Flatpak
  community.general.flatpak:
    name: com.visualstudio.code
    state: absent
...
