---
- name: Install Flatpaks
  become: true
  block:
    - name: Install Librewolf via Flatpak
      community.general.flatpak:
        name: io.gitlab.librewolf-community
        state: present

    - name: Install KeePassXC via Flatpak
      community.general.flatpak:
        name: org.keepassxc.KeePassXC
        state: present

    - name: Install Mozilla Thunderbird via Flatpak
      community.general.flatpak:
        name: org.mozilla.Thunderbird
        state: present

    - name: Install Fedora Media Writer via Flatpak
      community.general.flatpak:
        name: org.fedoraproject.MediaWriter
        state: present
...
