---
- name: Install Common Packages
  hosts: all
  become: true
  tasks:
    - name: Install common packages
      package:
        name:
          - curl
          - wget
          - tmux
          - tree
          - stow
          - htop
          - btop
          - bat
          - neovim
        state: present
