---
- name: Setup dotfiles on remote machine
  hosts: all
  become: false
  vars:
    dotfiles_repo: "git@github.com:robpellegrin/dotfiles.git"
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Set user home directory
      set_fact:
        user_home: "{{ ansible_facts['env']['HOME'] }}"

    - name: Ensure ~/.ssh directory exists
      file:
        path: "{{ user_home }}/.ssh"
        state: directory
        mode: '0700'

    - name: Copy local SSH public key to remote authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: Copy the SSH private key to remote machine
      copy:
        src: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
        dest: "{{ user_home }}/.ssh/id_ed25519"
        mode: '0600'

    - name: Start SSH agent and add private key
      shell: |
        eval $(ssh-agent)
        ssh-add {{ user_home }}/.ssh/id_ed25519
      args:
        executable: /bin/bash

    - name: Install GNU stow
      become: true
      ansible.builtin.package:
        name: stow
        state: present

    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ user_home }}/dotfiles"
        version: HEAD
        update: yes
        accept_hostkey: yes

    - name: Run stow --adopt .
      shell: stow --adopt .
      args:
        chdir: "{{ user_home }}/dotfiles"

    - name: Run git restore .
      shell: git restore .
      args:
        chdir: "{{ user_home }}/dotfiles"
...