---
- name: Install Flatpak and Librewolf
  hosts: all
  become: true
  tasks:
    - name: Install Flatpak
      package:
        name: flatpak
        state: present

    - name: Add Flathub repository to Flatpak
      shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/exports/repo/flathub.flatpakrepo  # Ensures Flathub is only added once

    - name: Install Librewolf via Flatpak
      flatpak:
        name: io.gitlab.librewolf-community
        state: present
...
