---
- name: Install Rust programming language using rustup
  hosts: all
  become: yes
  vars:
    rust_install_script_url: https://sh.rustup.rs
    rust_user: "{{ ansible_user }}"  # You can override this if needed

  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Download and install Rust using rustup
      become: false
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf {{ rust_install_script_url }} | sh -s -- -y
      args:
        executable: /bin/bash
        chdir: "/home/{{ rust_user }}"
        creates: "/home/{{ rust_user }}/.cargo/bin/rustc"

    - name: Add Rust environment to user's .bashrc
      become: false
      lineinfile:
        path: "/home/{{ rust_user }}/.bashrc"
        line: 'source $HOME/.cargo/env'
        insertafter: EOF
        create: yes
...
