---
- name: Install and build Neovim from source
  hosts: all
  become: true
  vars:
    neovim_repo: https://github.com/neovim/neovim
    neovim_clone_dest: /tmp/neovim
    neovim_build_type: RelWithDebInfo

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - git
          - make
          - build-essential
          - shfmt
          - clangd
          - npm
          - clang-format
        state: present
        update_cache: true

    - name: Remove existing Neovim directory if it exists
      file:
        path: "{{ neovim_clone_dest }}"
        state: absent

    - name: Clone Neovim repository
      git:
        repo: "{{ neovim_repo }}"
        dest: "{{ neovim_clone_dest }}"
        version: master

    - name: Build Neovim
      command: make CMAKE_BUILD_TYPE={{ neovim_build_type }}
      args:
        chdir: "{{ neovim_clone_dest }}"

    - name: Install Neovim
      command: make install
      args:
        chdir: "{{ neovim_clone_dest }}"
...
