---
- name: Install Rust via rustup script
  hosts: all
  become: false
  vars:
    rust_script_url: "https://sh.rustup.rs"
    rust_script_dest: "/tmp/rustup-init.sh"
    rust_home: "/home/{{ ansible_user }}"
  tasks:
    - name: Ensure curl is installed
      become: true
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download Rust installation script
      ansible.builtin.get_url:
        url: "{{ rust_script_url }}"
        dest: "{{ rust_script_dest }}"
        mode: '0755'

    - name: Run Rust installation script
      ansible.builtin.shell: |
        set -o pipefail
        "{{ rust_script_dest }}" -y | tee /tmp/rust_install.log
      args:
        executable: /bin/bash
        chdir: "{{ rust_home }}"
        creates: "{{ rust_home }}/.cargo/bin/rustc"

    - name: Ensure Rust environment is sourced in .bashrc
      ansible.builtin.lineinfile:
        path: "{{ rust_home }}/.bashrc"
        line: 'source "$HOME/.cargo/env"'
        create: true
        state: present
        mode: "0600"

    - name: Check if 'eza' is in the PATH
      ansible.builtin.command: which eza
      register: eza_check
      ignore_errors: true
      changed_when: eza_check.rc != 0

    - name: Install 'eza' with cargo if not present
      ansible.builtin.command: cargo install { eza }
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      when: eza_check.rc != 0
      changed_when: eza_check.rc != 0
...
