---
- name: Install Common Packages
  package:
    name:
      - python3-dnf # Needed for Ansible to interact with DNF.
      - curl
      - wget
      - tree
      - htop
      - btop
      - bat
      - eza
    state: present
...