---
- name: Install Flatpak
  package:
    name: "{{ flatpak_package_name }}"
    state: present

- name: Add Flathub repository to Flatpak
  shell: flatpak remote-add --if-not-exists flathub "{{ flathub_repo_url }}"
  args:
    creates: "{{ flathub_repo_path }}"  # Ensures Flathub is only added once
...