---
- name: Configure firefox
  become: true
  block:
    - name: Ensure Firefox is installed
      ansible.builtin.package:
        name: firefox
        state: present

    - name: Copy firefox.cfg to the specified path
      ansible.builtin.copy:
        src: firefox.cfg
        dest: "{{ firefox_cfg_path }}"
        mode: '0644'

    - name: Copy autoconfig.js to the specified path
      ansible.builtin.copy:
        src: autoconfig.js
        dest: "{{ firefox_autoconfig_js_path }}"
        mode: '0644'

    - name: Ensure the policies directory exists
      ansible.builtin.file:
        path: "{{ firefox_policies_dir }}"
        state: directory
        mode: '0755'

    - name: Copy policies.json to the specified path
      ansible.builtin.copy:
        src: policies.json
        dest: "{{ firefox_policies_json_path }}"
        mode: '0644'
...
