---
- name: Check reachability of nodes
  hosts: cluster_nodes
  gather_facts: false  # Skip gathering facts for faster execution
  tasks:
    - name: Check if the node is reachable
      ping:
      register: ping_result
      ignore_errors: yes  # Allow the playbook to continue even if some nodes are unreachable

    - name: Display reachable nodes
      debug:
        msg: "Node {{ inventory_hostname }} is reachable."
      when: ping_result.ping == "pong"

    - name: Display unreachable nodes
      debug:
        msg: "Node {{ inventory_hostname }} is unreachable."
      when: ping_result.failed

    - name: Resolve user home directory
      ansible.builtin.command: "echo ~{{ ansible_user }}"
      register: home_dir

    - name: Check if ~/MPI is a mounted NFS volume
      ansible.builtin.shell: |
        mountpoint -q {{ home_dir.stdout }}/MPI && grep -qs "{{ home_dir.stdout }}/MPI" /proc/mounts && [ "$(ls -A {{ home_dir.stdout }}/MPI)" ]
      register: nfs_check
      failed_when: false
      changed_when: false

    - name: Report status
      ansible.builtin.debug:
        msg: >
          NFS volume is {{ 'mounted and not empty' if nfs_check.rc == 0 else 'not mounted or empty' }} at {{ home_dir.stdout }}/MPI
...