---
hyprland_copr_repo: "solopasha/hyprland"
dnf_plugins_package: "dnf-plugins-core"
repo_file_path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:solopasha:hyprland.repo"

hyprland_packages:
  - hyprland
  - xdg-desktop-portal-hyprland
  - waybar
  - rofi
  - kitty
  - wl-clipboard
  - wlsunset
  - grim
  - slurp
  - swaybg
  - swappy
  - playerctl
  - network-manager-applet
  - dunst
  - hyprpaper
  - hyprlock

# Environment variable to disable hardware cursors in Hyprland
wlr_no_hardware_cursors: "WLR_NO_HARDWARE_CURSORS=1"

...