---
hyprland_copr_repo: "solopasha/hyprland"
hyprland_dnf_plugins_package: "dnf-plugins-core"
hyprland_repo_file_path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:solopasha:hyprland.repo"
hyprland_local_wallpaper_path: "{{ lookup('env', 'HOME') }}/Pictures/wallpaper.png"
hyprland_remote_wallpaper_path: "/home/{{ ansible_user }}/Pictures/wallpaper.png"

hyprland_packages:
  - hyprland
  - xdg-desktop-portal-hyprland
  - waybar
  - rofi
  - kitty
  - wl-clipboard
  - playerctl
  - network-manager-applet
  - swaync
  - hyprpaper
  - hyprlock
  - hyprsunset

# Environment variable to disable hardware cursors in Hyprland
hyprland_wlr_no_hardware_cursors: "WLR_NO_HARDWARE_CURSORS=1"

...
