---
secure_sysctl_settings_settings:
  - dev.tty.ldisc_autoload = 0
  - fs.protected_fifos = 2
  - fs.protected_regular = 2
  - fs.suid_dumpable = 0
  - kernel.kptr_restrict = 2
  - kernel.sysrq = 0
  - kernel.unprivileged_bpf_disabled = 1
  - net.core.bpf_jit_harden = 2
  - net.ipv4.conf.all.log_martians = 1
  - net.ipv4.conf.all.rp_filter = 1
  - net.ipv4.conf.default.log_martians = 1
...
