---
- name: Ensure curl is installed
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Download Rust install script
  ansible.builtin.get_url:
    url: "{{ install_rust_script_url }}"
    dest: "/home/{{ ansible_user }}/rustup-init.sh"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Rust install script
  become: false
  ansible.builtin.command: ./rustup-init.sh -y
  args:
    chdir: "/home/{{ ansible_user }}"
    creates: "/home/{{ ansible_user }}/.cargo/bin/rustc"

- name: Add Rust environment to .custom_path
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.custom_path"
    line: 'source $HOME/.cargo/env'
    insertafter: EOF
    create: true
    mode: "0600"
...
