---
# tasks file for rust_install role

- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Download and install Rust using rustup
  become: false
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf {{ rust_install_script_url }} | sh -s -- -y
  args:
    executable: /bin/bash
    chdir: "/home/{{ ansible_user }}"
    creates: "/home/{{ ansible_user }}/.cargo/bin/rustc"

- name: Add Rust environment to user's .bashrc
  become: false
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'source $HOME/.cargo/env'
    insertafter: EOF
    create: yes
...