---
- name: Install packages from the Debian repository
  hosts: all
  become: yes  # Ensure the tasks are run with root privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenMPI and related packages
      apt:
        name:
          - build-essential
          - nfs-common
          - libopenmpi-dev
        state: present

    - name: Install mpich
      apt:
        name:
          - libmpich-dev
        state: present

    - name: Install extras (ln-sensors, btop, etc)
      apt:
        name:
          - lm-sensors
          - htop
          - btop
        state: present

    - name: Install BLAS library
      apt:
        name:
          - libblas-dev
        state: present
...