---
- name: Install packages from the Debian repository
  hosts: all
  become: yes  # Ensure the tasks are run with root privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - lm-sensors
          - htop
          - build-essential
          - libopenmpi-dev
          - nfs-common
          - btop
        state: present
