---
- name: Shutdown all nodes
  hosts: all
  become: true
  tasks:
    - name: Shutdown the node
      ansible.builtin.command: systemctl poweroff
      async: 1  # Run the shutdown command in the background
      poll: 0   # Don't wait for the shutdown command to finish
