- name: Harden SSH parameters
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    state: present
    create: true
    backup: true
    mode: "0600"
  loop: "{{ ssh_parameters }}"
...
