---
- name: Ensure DNF config settings are present
  hosts: all
  become: yes
  tasks:
    - name: Ensure 'fastestmirror=True' is present in /etc/dnf/dnf.conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^fastestmirror='
        line: 'fastestmirror=True'
        insertafter: '^\[main\]'

    - name: Ensure 'max_parallel_downloads=15' is present in /etc/dnf/dnf.conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^max_parallel_downloads='
        line: 'max_parallel_downloads=15'
        insertafter: '^\[main\]'
...