---
- name: Set secured sysctl values
  hosts: all
  become: true

  tasks:
    - name: Ensure /etc/sysctl.d/60-secured-values.conf contains the desired sysctl settings
      copy:
        dest: /etc/sysctl.d/60-secured-values.conf
        mode: '0644'
        owner: root
        group: root
        content: |
          kernel.yama.ptrace_scope = 3 # Can cause problems. 
          dev.tty.ldisc_autoload = 0
          fs.protected_fifos = 2
          fs.protected_regular = 2
          fs.suid_dumpable = 0
          kernel.kptr_restrict = 2
          kernel.sysrq = 0
          kernel.unprivileged_bpf_disabled = 1
          net.core.bpf_jit_harden = 2
          net.ipv4.conf.all.log_martians = 1
          net.ipv4.conf.all.rp_filter = 1
          net.ipv4.conf.default.log_martians = 1
...