---
- name: Harden SSH configuration
  hosts: all
  become: yes

  tasks:

    - name: Backup existing sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes
        backup: yes

    - name: Set recommended SSH parameters
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
        state: present
        create: yes
        backup: no
      loop:
        - { key: 'AllowTcpForwarding', value: 'no' }
        - { key: 'ClientAliveCountMax', value: '2' }
        - { key: 'LogLevel', value: 'VERBOSE' }
        - { key: 'MaxAuthTries', value: '3' }
        - { key: 'MaxSessions', value: '2' }
        - { key: 'TCPKeepAlive', value: 'no' }
        - { key: 'X11Forwarding', value: 'no' }
        - { key: 'AllowAgentForwarding', value: 'no' }
        # Uncomment and customize to change the port
        # - { key: 'Port', value: '2222' }

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
        enabled: yes
...