- name: Install required system packages and configure environment
  become: true
  block:
    - name: Ensure dnf-plugins-core is installed (needed for copr)
      ansible.builtin.package:
        name: "{{ hyprland_dnf_plugins_package }}"
        state: present

    - name: Enable solopasha/hyprland Copr repository
      ansible.builtin.command: dnf copr enable -y {{ hyprland_copr_repo }}
      args:
        creates: "{{ hyprland_repo_file_path }}"

    - name: Refresh DNF metadata
      ansible.builtin.command: dnf makecache
      changed_when: false

    - name: Install Hyprland and related packages
      ansible.builtin.package:
        name: "{{ hyprland_packages }}"
        state: present

    - name: Ensure WLR_NO_HARDWARE_CURSORS is set in /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ hyprland_wlr_no_hardware_cursors }}"
        create: true
        state: present
        mode: "0600"

- name: Ensure remote Pictures directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Pictures"
    state: directory
    mode: '0755'

- name: Copy wallpaper.png to remote Pictures folder
  ansible.builtin.copy:
    src: "{{ hyprland_local_wallpaper_path }}"
    dest: "{{ hyprland_remote_wallpaper_path }}"
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
...
