---
# tasks file for hyprland_repo role

- name: Ensure dnf-plugins-core is installed (needed for copr)
  package:
    name: "{{ dnf_plugins_package }}"
    state: present

- name: Enable solopasha/hyprland Copr repository
  command: dnf copr enable -y {{ hyprland_copr_repo }}
  args:
    creates: "{{ repo_file_path }}"

- name: Refresh DNF metadata
  command: dnf makecache

- name: Update all packages to the latest version
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install Hyprland and related packages
  ansible.builtin.package:
    name: "{{ hyprland_packages }}"
    state: present

- name: Ensure WLR_NO_HARDWARE_CURSORS is set in /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ wlr_no_hardware_cursors }}"
    create: yes
    state: present

- name: Ensure remote Pictures directory exists
  file:
    path: "{{ ansible_env.HOME }}/Pictures"
    state: directory
    mode: '0755'

- name: Copy wallpaper.png to remote Pictures folder
  copy:
    src: "{{ local_wallpaper_path }}"
    dest: "{{ remote_wallpaper_path }}"
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
...
