---
- name: Harden SSH
  become: true
  block:
    - name: Harden SSH parameters
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
        state: present
        create: true
        backup: true
        mode: "0600"
      loop: "{{ harden_ssh_parameters }}"
...
