---
- name: Install development tools
  become: true
  ansible.builtin.package:
    name:
      - git
      - neovim
      - valgrind
      - gcc
      - g++
      - make
      - cppcheck
    state: present
...
