---
- name: Install Hyprland from Fedora repos
  hosts: all
  become: true

  vars:
    hyprland_packages:
      - hyprland
      - xdg-desktop-portal-hyprland
      - waybar
      - rofi
      - kitty
      - wl-clipboard
      - wlsunset
      - grim
      - slurp
      - swaybg
      - swappy
      - playerctl
      - network-manager-applet
      - dunst

  tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Install Hyprland and tools
      ansible.builtin.package:
        name: "{{ hyprland_packages }}"
        state: present

    - name: Ensure WLR_NO_HARDWARE_CURSORS is set in /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'WLR_NO_HARDWARE_CURSORS=1'
        create: yes
        state: present
...
