---
# main.yaml for system_config role
# This file includes various configuration tasks

- name: Include configure DNF settings
  include_tasks: configure-dnf.yaml

- name: Include disable core dumps configuration
  include_tasks: disable-core-dumps.yaml

- name: Include disable protocols configuration
  include_tasks: disable-protocols.yaml

- name: Apply secure sysctl settings
  include_tasks: secure-sysctl.yaml

- name: Set UMASK to 027 in /etc/login.defs
  include_tasks: set-umask.yaml

- name: Harden SSH configuration
  include_tasks: ssh-config.yaml

- name: Disable unused services
  include_tasks: disable-unused-services.yaml
...