---
- name: Reload modprobe
  ansible.builtin.command: /sbin/modprobe -r dccp sctp rds tipc
  when: ansible_facts.os_family == "Debian" or ansible_facts.os_family == "RedHat"
  ignore_errors: yes

- name: Reload systemd
  systemd:
    name: "{{ item }}"
    state: reloaded
  loop: "{{ disabled_services }}"
...