---
- name: Configure fedora system
  hosts: all
  roles:
    #- dotfile_setup
    #- hyprland
    - terminal_setup
    #- install_rust
    #- disable_core_dump
    #- harden_ssh
    #- configure_dnf
    #- firefox
    #- flatpak_repo
    #- flatpak_packages
...
