---
- name: Configure Fedora system
  hosts: all
  roles:
    - common_packages
    - configure_dnf
    - dotfile_setup
    - firefox
    - terminal_setup
    - hyprland
    - flatpak_repo
    - flatpak_packages
    - disable_core_dump
    - harden_ssh
    # - install_rust
...
