---
- name: Configure Fedora system
  hosts: all
  roles:
    - configure_dnf # Should remain first role.
    - common_packages
    - dotfile_setup
    - firefox
    - terminal_setup
    - hyprland
    - flatpak_repo
    - flatpak_packages
    - disable_core_dump
    - harden_ssh
    # - install_rust
...
