---
- name: Disable systemd services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items: "{{ disable_unused_services_disabled_services }}"
  when: disable_unused_services_disabled_services is defined
  tags:
    - disable_services
...
